In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import math

In [2]:
dataframe=pd.read_csv('homeprices.csv')

In [3]:
dataframe


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
dataframe.head

<bound method NDFrame.head of    area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000>

In [5]:
dataframe.head()


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())

NameError: name 'df' is not defined

In [7]:
dataframe.bedrooms=dataframe.bedrooms.fillna(dataframe.bedrooms.median())

In [8]:
dataframe
#midean is 4.0

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
model=linear_model.LinearRegression()

In [10]:
model.fit(dataframe[['area','bedrooms','age']],dataframe.price)

LinearRegression()

In [12]:
model.predict([[2600,1000,1]])

C:\Users\Sarthak\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23898333.71094548])

In [13]:
import pickle


In [15]:
with open ('model_pickle','wb') as f:
    pickle.dump(model,f)
#this is used to save a model into a file
#  b=binary
#  wb=writebinary  (write+binary respetively) used to  write binary files

In [19]:
with open ('model_pickle','rb') as f:
    mp=pickle.load(f)
#loading up the trained model (model) to the code for usage
#  rb=readbinary  (read+binary respetively) used to read binary files

In [18]:
mp.predict([[5000,3,4]])

C:\Users\Sarthak\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([838874.98017536])

In [23]:
import joblib

In [25]:
mj=joblib.dump(model,'model_joblib')

# mj=model joblib
#creates saved model using joblib

In [27]:
mj=joblib.load('model_joblib')

In [28]:
mj.predict([[5000,3,4]])

C:\Users\Sarthak\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([838874.98017536])

In [ ]:
#here we see the prediction is the same down to the point so these were the two methods to save/load models onto a file

#joblib and pickle are used to save model states but joblib is more efficient when we are working with a large number of 
#numpy data such as numpy arrays but essentially  both have the same functionality